Views
Elhambasir/blog-app pull request #10
Opened 2023-07-26 18:09 UTC by Elhambasir

### What is done in this PR?
In this project, I added the Views associated with the Models and Controllers I've already created for my Blog App.

- [x] Implemented the design from the sneak peek wireframes.
- [x] All functionality for index and show action is done in user and post controllers.

[PROJECT REQUIREMENTS](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)

Thank you for reviewing.

2023-07-26 20:34 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @Elhambasir 

Good job so far 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 20:34 UTC, KanzaTahreem commented on config/routes.rb
- [x] Please make sure that the default Rails page is replaced with the user's index page as shown in the wireframe. 💪  To ensure that the user's index page is displayed when the app starts, we just need to add root `'users#index'` to the `routes.rb` file.

Current Page | Expected Page
---| ---|
![image](https://github.com/Elhambasir/blog-app/assets/106119105/9a72624e-58c5-43ac-a4b4-46ab869413bb) | ![image](https://github.com/Elhambasir/blog-app/assets/106119105/7f720e93-bb16-473a-a8df-65d1c17ad21d)

2023-07-26 20:34 UTC, KanzaTahreem commented on app/views/users/show.html.erb
> +  <% end %>
- [x] Good job so far 👍👍 However, instead of displaying all of the user's posts, let's make use of the `recent_posts` method available in `user.rb` to showcase only the user's three most recent posts as mentioned in the wireframe. This will provide a more concise and relevant view for the user's posts. What do you think about it ?✨😀

Present UI | Expected UI
---| ---|
![image](https://github.com/Elhambasir/blog-app/assets/106119105/30906be8-f870-48fa-9bdd-7082a7078357) | ![image](https://github.com/Elhambasir/blog-app/assets/106119105/aff82947-5e40-4d91-aa2f-4b5d0112622e)



- [x] When I am clicking on the first post of the first user, it is redirecting to the first user's post index page. But when I am clicking on the second post of the first user, it is redirecting to the second user's post index page and so on ⚠ Kindly have at look at the following video for better clarity 💡 Please make sure to fix this bug 🐛



https://github.com/Elhambasir/blog-app/assets/106119105/8ea80b79-6d1f-4442-9601-18fe11cf4afb

2023-07-26 20:34 UTC, KanzaTahreem commented on app/views/posts/index.html.erb
> +    <% end %>
- [x] Similarly here, please ensure that you use the `recent_comments` method, which is present in the `post.rb` model, to render only the five most recent comments for each post. Currently, all comments are being rendered, which is not the desired behavior. according to the [wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_all_posts.png?token=GHSAT0AAAAAAB5V373VUXJOQCI3SIRAY6FCZGBPCJA)✨ 

_This is what you have in the user's post index page_

![image](https://github.com/Elhambasir/blog-app/assets/106119105/0e6b6094-06da-41db-a1f8-8e0a4e5a4351)



- [x] Kindly have a look at this behavior 👇 When I am clicking on first user's first post on post index page, I'm redirecting to first user's post show page with the correct url. However, when I am clicking on the second post, although it is redirecting to the first user's post show page but the url is not correct. Please make sure to fix this ✨


https://github.com/Elhambasir/blog-app/assets/106119105/341184ad-9b9a-43ad-8a89-ecf4f88aeddd

2023-07-26 20:34 UTC, KanzaTahreem commented on app/views/users/show.html.erb
> +      <button class="btn btn-secandary">See more posts</button>
- [x] The **_See more posts_** is not redirecting to the post index page. Please make sure that this is a link which opens user's post index as displayed on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)📌⛏

2023-07-27 12:37 UTC, Elhambasir commented on config/routes.rb
Fixed

2023-07-27 12:38 UTC, Elhambasir commented on app/views/users/show.html.erb
> +  <% end %>
Thank you I fixed that

2023-07-27 12:38 UTC, Elhambasir commented on app/views/posts/index.html.erb
> +    <% end %>
Got fixed

2023-07-27 12:38 UTC, Elhambasir commented on app/views/users/show.html.erb
> +      <button class="btn btn-secandary">See more posts</button>
Thank you

2023-07-27 14:24 UTC, BregornOriginal requested changes
Hi @Elhambasir  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![hand-sketching-stair-slogan-one-step-closer-chalkboard-79948193](https://github.com/Elhambasir/blog-app/assets/93630700/5bfa2e00-1fd0-4657-89db-2ac46b30f6c7)

 ## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good work implementing some changes! 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 14:24 UTC, BregornOriginal commented on config/routes.rb
@Elhambasir Kindly as was suggested by the previous reviewer. Add `'users#index'` to your `routes.rb` config file

2023-07-27 14:24 UTC, BregornOriginal commented on app/views/users/show.html.erb
> +      <button class="btn btn-secandary">See more posts</button>
- [ ] Kindly as was requested by the previous reviewer, make sure the button `See more posts` redirects to the list of posts of the user

2023-07-27 14:24 UTC, BregornOriginal commented on app/views/posts/index.html.erb
> +  <% @posts.each_with_index do |post,index| %>
- [ ] Kindly make sure to show correctly the `posts#index` page, while running the page there's an error on it

![image](https://github.com/Elhambasir/blog-app/assets/93630700/57740a90-d3c5-4778-b48b-b0925f372051)

2023-07-27 15:02 UTC, rotimiazeez approved these changes
Hi @Elhambasir 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job working on the required changes 👍🏽
- Good App UI 👌🏽
- Good PR description and summary 👏🏽

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 15:02 UTC, merged